config/routes.rb
Thisamericanlife::Application.routes.draw do

  constraints :subdomain => "api" do
    scope :module => "api" do
      get '/random' => 'episodes#random'
      get '/q' => 'episodes#search'
      get '/:id' => 'episodes#show'
      get '/' => 'episodes#index'
    end
  end

  root 'episodes#index'

  get '/import' => 'episodes#import', as: :import
  get '/seed' => 'episodes#seed', as: :seed
  get '/about' => 'episodes#about', as: :about
  get '/search' => 'episodes#search', as: :search
  get '/:id' => 'episodes#show', as: :title

  namespace :admin do
    resources :episodes
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title><%= "#{@episode['number']}: #{@episode['title']} | " if @episode %>This American Life</title>

		<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" href="/css/app.css" type="text/css">

    <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

		<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-44211034-4', 'auto');
      ga('send', 'pageview');
		</script>

	</head>
	<body>
		<div class="container">
			<div class="col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
				<div class="row">
					<h1><a href="/"><span class="blue">THIS</span> <span class="red">AMERICAN</span> <span class="blue">LIFE</span></a></h1>

					<% if new_episode? %>
            <%= link_to "IMPORT NEW EPISODE!", import_path, class: "btn btn-primary btn-block" %>
          <% end %>

          <% unless action_name == "about" || params[:random] || current_page?(admin_episodes_path)%>
            <form action="<%= search_path %>" method="get">
              <%= text_field_tag :q, params[:q], class: 'form-control input-lg', placeholder: "search: type and then hit enter" %>
            </form>
          <% end %>

          <% flash.each do |key, value| %>
            <% key = key == "alert" ? "danger" : "info" %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>

					<%= yield %>

          <div id="footer">
            <ul class="list-inline text-center">
              <li><%= link_to "about", about_path %></li>
              <li><%= link_to "eliduke.com", "http://eliduke.com", target: "_blank" %> </li>
              <li><%= link_to "admin", admin_episodes_path %> </li>
            </ul>
          </div>
				</div>
			</div>
		</div>
	</body>
</html>